// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cugmhcbrnqfmmkvmfdad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Z21oY2JybnFmbW1rdm1mZGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTk2NDMsImV4cCI6MjA2ODA3NTY0M30.69Yq4H5ZQgIGfXIDeg-Uw9ULazQZY4w_-16Z1sSJj4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});